// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.0
// source: recommendation/recommendation-service.proto

package recommendation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recommendation_recommendation_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_recommendation_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_recommendation_recommendation_service_proto_rawDescGZIP(), []int{0}
}

type RecommendedAccommodations_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*RecommendedAccommodationDTO `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *RecommendedAccommodations_Response) Reset() {
	*x = RecommendedAccommodations_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recommendation_recommendation_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecommendedAccommodations_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendedAccommodations_Response) ProtoMessage() {}

func (x *RecommendedAccommodations_Response) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_recommendation_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendedAccommodations_Response.ProtoReflect.Descriptor instead.
func (*RecommendedAccommodations_Response) Descriptor() ([]byte, []int) {
	return file_recommendation_recommendation_service_proto_rawDescGZIP(), []int{1}
}

func (x *RecommendedAccommodations_Response) GetData() []*RecommendedAccommodationDTO {
	if x != nil {
		return x.Data
	}
	return nil
}

type RecommendedAccommodationDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Benefits  string  `protobuf:"bytes,3,opt,name=benefits,proto3" json:"benefits,omitempty"`
	MinGuests int32   `protobuf:"varint,4,opt,name=minGuests,proto3" json:"minGuests,omitempty"`
	MaxGuests int32   `protobuf:"varint,5,opt,name=maxGuests,proto3" json:"maxGuests,omitempty"`
	BasePrice float64 `protobuf:"fixed64,6,opt,name=basePrice,proto3" json:"basePrice,omitempty"`
}

func (x *RecommendedAccommodationDTO) Reset() {
	*x = RecommendedAccommodationDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recommendation_recommendation_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecommendedAccommodationDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendedAccommodationDTO) ProtoMessage() {}

func (x *RecommendedAccommodationDTO) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_recommendation_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendedAccommodationDTO.ProtoReflect.Descriptor instead.
func (*RecommendedAccommodationDTO) Descriptor() ([]byte, []int) {
	return file_recommendation_recommendation_service_proto_rawDescGZIP(), []int{2}
}

func (x *RecommendedAccommodationDTO) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RecommendedAccommodationDTO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RecommendedAccommodationDTO) GetBenefits() string {
	if x != nil {
		return x.Benefits
	}
	return ""
}

func (x *RecommendedAccommodationDTO) GetMinGuests() int32 {
	if x != nil {
		return x.MinGuests
	}
	return 0
}

func (x *RecommendedAccommodationDTO) GetMaxGuests() int32 {
	if x != nil {
		return x.MaxGuests
	}
	return 0
}

func (x *RecommendedAccommodationDTO) GetBasePrice() float64 {
	if x != nil {
		return x.BasePrice
	}
	return 0
}

var File_recommendation_recommendation_service_proto protoreflect.FileDescriptor

var file_recommendation_recommendation_service_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2f, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2d,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0e, 0x0a,
	0x0c, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x56, 0x0a,
	0x22, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x41,
	0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x54, 0x4f, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xb7, 0x01, 0x0a, 0x1b, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x64, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x44, 0x54, 0x4f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x65, 0x6e,
	0x65, 0x66, 0x69, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x65, 0x6e,
	0x65, 0x66, 0x69, 0x74, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x69, 0x6e, 0x47, 0x75, 0x65, 0x73,
	0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x69, 0x6e, 0x47, 0x75, 0x65,
	0x73, 0x74, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x78, 0x47, 0x75, 0x65, 0x73, 0x74, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x61, 0x78, 0x47, 0x75, 0x65, 0x73, 0x74,
	0x73, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x62, 0x61, 0x73, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x32,
	0x6d, 0x0a, 0x15, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x54, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x0d, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x64, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x16,
	0x5a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_recommendation_recommendation_service_proto_rawDescOnce sync.Once
	file_recommendation_recommendation_service_proto_rawDescData = file_recommendation_recommendation_service_proto_rawDesc
)

func file_recommendation_recommendation_service_proto_rawDescGZIP() []byte {
	file_recommendation_recommendation_service_proto_rawDescOnce.Do(func() {
		file_recommendation_recommendation_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_recommendation_recommendation_service_proto_rawDescData)
	})
	return file_recommendation_recommendation_service_proto_rawDescData
}

var file_recommendation_recommendation_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_recommendation_recommendation_service_proto_goTypes = []interface{}{
	(*EmptyRequest)(nil),                       // 0: EmptyRequest
	(*RecommendedAccommodations_Response)(nil), // 1: RecommendedAccommodations_Response
	(*RecommendedAccommodationDTO)(nil),        // 2: RecommendedAccommodationDTO
}
var file_recommendation_recommendation_service_proto_depIdxs = []int32{
	2, // 0: RecommendedAccommodations_Response.data:type_name -> RecommendedAccommodationDTO
	0, // 1: RecommendationService.GetRecommendedAccommodations:input_type -> EmptyRequest
	1, // 2: RecommendationService.GetRecommendedAccommodations:output_type -> RecommendedAccommodations_Response
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_recommendation_recommendation_service_proto_init() }
func file_recommendation_recommendation_service_proto_init() {
	if File_recommendation_recommendation_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_recommendation_recommendation_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recommendation_recommendation_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecommendedAccommodations_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recommendation_recommendation_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecommendedAccommodationDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_recommendation_recommendation_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recommendation_recommendation_service_proto_goTypes,
		DependencyIndexes: file_recommendation_recommendation_service_proto_depIdxs,
		MessageInfos:      file_recommendation_recommendation_service_proto_msgTypes,
	}.Build()
	File_recommendation_recommendation_service_proto = out.File
	file_recommendation_recommendation_service_proto_rawDesc = nil
	file_recommendation_recommendation_service_proto_goTypes = nil
	file_recommendation_recommendation_service_proto_depIdxs = nil
}
