// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.4
// source: rating/rating-service.proto

package rating

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_rating_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_rating_rating_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_rating_rating_service_proto_rawDescGZIP(), []int{0}
}

type CreateAccommodationRatingDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccommodationId string `protobuf:"bytes,1,opt,name=AccommodationId,proto3" json:"AccommodationId,omitempty"`
	Value           uint32 `protobuf:"varint,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *CreateAccommodationRatingDTO) Reset() {
	*x = CreateAccommodationRatingDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_rating_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAccommodationRatingDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccommodationRatingDTO) ProtoMessage() {}

func (x *CreateAccommodationRatingDTO) ProtoReflect() protoreflect.Message {
	mi := &file_rating_rating_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccommodationRatingDTO.ProtoReflect.Descriptor instead.
func (*CreateAccommodationRatingDTO) Descriptor() ([]byte, []int) {
	return file_rating_rating_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccommodationRatingDTO) GetAccommodationId() string {
	if x != nil {
		return x.AccommodationId
	}
	return ""
}

func (x *CreateAccommodationRatingDTO) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type CreateHostRatingDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostId string `protobuf:"bytes,1,opt,name=HostId,proto3" json:"HostId,omitempty"`
	Value  uint32 `protobuf:"varint,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *CreateHostRatingDTO) Reset() {
	*x = CreateHostRatingDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_rating_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHostRatingDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHostRatingDTO) ProtoMessage() {}

func (x *CreateHostRatingDTO) ProtoReflect() protoreflect.Message {
	mi := &file_rating_rating_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHostRatingDTO.ProtoReflect.Descriptor instead.
func (*CreateHostRatingDTO) Descriptor() ([]byte, []int) {
	return file_rating_rating_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateHostRatingDTO) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *CreateHostRatingDTO) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type RatingsList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*RatingDTO `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
}

func (x *RatingsList) Reset() {
	*x = RatingsList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_rating_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RatingsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatingsList) ProtoMessage() {}

func (x *RatingsList) ProtoReflect() protoreflect.Message {
	mi := &file_rating_rating_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatingsList.ProtoReflect.Descriptor instead.
func (*RatingsList) Descriptor() ([]byte, []int) {
	return file_rating_rating_service_proto_rawDescGZIP(), []int{3}
}

func (x *RatingsList) GetData() []*RatingDTO {
	if x != nil {
		return x.Data
	}
	return nil
}

type RatingDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	UserId     string `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	TargetId   string `protobuf:"bytes,3,opt,name=TargetId,proto3" json:"TargetId,omitempty"`
	TargetType uint32 `protobuf:"varint,4,opt,name=TargetType,proto3" json:"TargetType,omitempty"`
	Value      uint32 `protobuf:"varint,5,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *RatingDTO) Reset() {
	*x = RatingDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rating_rating_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RatingDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatingDTO) ProtoMessage() {}

func (x *RatingDTO) ProtoReflect() protoreflect.Message {
	mi := &file_rating_rating_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatingDTO.ProtoReflect.Descriptor instead.
func (*RatingDTO) Descriptor() ([]byte, []int) {
	return file_rating_rating_service_proto_rawDescGZIP(), []int{4}
}

func (x *RatingDTO) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RatingDTO) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RatingDTO) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *RatingDTO) GetTargetType() uint32 {
	if x != nil {
		return x.TargetType
	}
	return 0
}

func (x *RatingDTO) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_rating_rating_service_proto protoreflect.FileDescriptor

var file_rating_rating_service_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x2f, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x2d,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x07, 0x0a, 0x05, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x5e, 0x0a, 0x1c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x61, 0x74, 0x69, 0x6e,
	0x67, 0x44, 0x54, 0x4f, 0x12, 0x28, 0x0a, 0x0f, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x41,
	0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x43, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x6f,
	0x73, 0x74, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x44, 0x54, 0x4f, 0x12, 0x16, 0x0a, 0x06, 0x48,
	0x6f, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x48, 0x6f, 0x73,
	0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2d, 0x0a, 0x0b, 0x52, 0x61, 0x74,
	0x69, 0x6e, 0x67, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x44,
	0x54, 0x4f, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x85, 0x01, 0x0a, 0x09, 0x52, 0x61, 0x74,
	0x69, 0x6e, 0x67, 0x44, 0x54, 0x4f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x54, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a,
	0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x32, 0xf8, 0x01, 0x0a, 0x0d, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x36, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0c, 0x2e, 0x52, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x0f, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x09, 0x12, 0x07, 0x2f, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x64, 0x0a, 0x19, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x1d, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x61, 0x74,
	0x69, 0x6e, 0x67, 0x44, 0x54, 0x4f, 0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x20,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1a, 0x3a, 0x01, 0x2a, 0x22, 0x15, 0x2f, 0x72, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x49, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73,
	0x74, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x44, 0x54, 0x4f, 0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x11, 0x3a, 0x01, 0x2a, 0x22, 0x0c, 0x2f,
	0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x2f, 0x68, 0x6f, 0x73, 0x74, 0x42, 0x0e, 0x5a, 0x0c, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_rating_rating_service_proto_rawDescOnce sync.Once
	file_rating_rating_service_proto_rawDescData = file_rating_rating_service_proto_rawDesc
)

func file_rating_rating_service_proto_rawDescGZIP() []byte {
	file_rating_rating_service_proto_rawDescOnce.Do(func() {
		file_rating_rating_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_rating_rating_service_proto_rawDescData)
	})
	return file_rating_rating_service_proto_rawDescData
}

var file_rating_rating_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_rating_rating_service_proto_goTypes = []interface{}{
	(*Empty)(nil),                        // 0: Empty
	(*CreateAccommodationRatingDTO)(nil), // 1: CreateAccommodationRatingDTO
	(*CreateHostRatingDTO)(nil),          // 2: CreateHostRatingDTO
	(*RatingsList)(nil),                  // 3: RatingsList
	(*RatingDTO)(nil),                    // 4: RatingDTO
}
var file_rating_rating_service_proto_depIdxs = []int32{
	4, // 0: RatingsList.Data:type_name -> RatingDTO
	0, // 1: RatingService.GetAllRatings:input_type -> Empty
	1, // 2: RatingService.CreateAccommodationRating:input_type -> CreateAccommodationRatingDTO
	2, // 3: RatingService.CreateHostRating:input_type -> CreateHostRatingDTO
	3, // 4: RatingService.GetAllRatings:output_type -> RatingsList
	0, // 5: RatingService.CreateAccommodationRating:output_type -> Empty
	0, // 6: RatingService.CreateHostRating:output_type -> Empty
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rating_rating_service_proto_init() }
func file_rating_rating_service_proto_init() {
	if File_rating_rating_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rating_rating_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_rating_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAccommodationRatingDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_rating_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHostRatingDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_rating_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RatingsList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rating_rating_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RatingDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rating_rating_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rating_rating_service_proto_goTypes,
		DependencyIndexes: file_rating_rating_service_proto_depIdxs,
		MessageInfos:      file_rating_rating_service_proto_msgTypes,
	}.Build()
	File_rating_rating_service_proto = out.File
	file_rating_rating_service_proto_rawDesc = nil
	file_rating_rating_service_proto_goTypes = nil
	file_rating_rating_service_proto_depIdxs = nil
}
