// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.4
// source: accommodation/accommodation-service.proto

package accommodation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AM_GetAllAccommodations_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AM_GetAllAccommodations_Request) Reset() {
	*x = AM_GetAllAccommodations_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accommodation_accommodation_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AM_GetAllAccommodations_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AM_GetAllAccommodations_Request) ProtoMessage() {}

func (x *AM_GetAllAccommodations_Request) ProtoReflect() protoreflect.Message {
	mi := &file_accommodation_accommodation_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AM_GetAllAccommodations_Request.ProtoReflect.Descriptor instead.
func (*AM_GetAllAccommodations_Request) Descriptor() ([]byte, []int) {
	return file_accommodation_accommodation_service_proto_rawDescGZIP(), []int{0}
}

type AM_GetAllAccommodations_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*AccommodationDTO `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *AM_GetAllAccommodations_Response) Reset() {
	*x = AM_GetAllAccommodations_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accommodation_accommodation_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AM_GetAllAccommodations_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AM_GetAllAccommodations_Response) ProtoMessage() {}

func (x *AM_GetAllAccommodations_Response) ProtoReflect() protoreflect.Message {
	mi := &file_accommodation_accommodation_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AM_GetAllAccommodations_Response.ProtoReflect.Descriptor instead.
func (*AM_GetAllAccommodations_Response) Descriptor() ([]byte, []int) {
	return file_accommodation_accommodation_service_proto_rawDescGZIP(), []int{1}
}

func (x *AM_GetAllAccommodations_Response) GetData() []*AccommodationDTO {
	if x != nil {
		return x.Data
	}
	return nil
}

type AM_CreateAccommodation_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Benefits  string  `protobuf:"bytes,2,opt,name=benefits,proto3" json:"benefits,omitempty"`
	MinGuests int32   `protobuf:"varint,3,opt,name=minGuests,proto3" json:"minGuests,omitempty"`
	MaxGuests int32   `protobuf:"varint,4,opt,name=maxGuests,proto3" json:"maxGuests,omitempty"`
	BasePrice float64 `protobuf:"fixed64,5,opt,name=basePrice,proto3" json:"basePrice,omitempty"`
}

func (x *AM_CreateAccommodation_Request) Reset() {
	*x = AM_CreateAccommodation_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accommodation_accommodation_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AM_CreateAccommodation_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AM_CreateAccommodation_Request) ProtoMessage() {}

func (x *AM_CreateAccommodation_Request) ProtoReflect() protoreflect.Message {
	mi := &file_accommodation_accommodation_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AM_CreateAccommodation_Request.ProtoReflect.Descriptor instead.
func (*AM_CreateAccommodation_Request) Descriptor() ([]byte, []int) {
	return file_accommodation_accommodation_service_proto_rawDescGZIP(), []int{2}
}

func (x *AM_CreateAccommodation_Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AM_CreateAccommodation_Request) GetBenefits() string {
	if x != nil {
		return x.Benefits
	}
	return ""
}

func (x *AM_CreateAccommodation_Request) GetMinGuests() int32 {
	if x != nil {
		return x.MinGuests
	}
	return 0
}

func (x *AM_CreateAccommodation_Request) GetMaxGuests() int32 {
	if x != nil {
		return x.MaxGuests
	}
	return 0
}

func (x *AM_CreateAccommodation_Request) GetBasePrice() float64 {
	if x != nil {
		return x.BasePrice
	}
	return 0
}

type AM_CreateAccommodation_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *AM_CreateAccommodation_Response) Reset() {
	*x = AM_CreateAccommodation_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accommodation_accommodation_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AM_CreateAccommodation_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AM_CreateAccommodation_Response) ProtoMessage() {}

func (x *AM_CreateAccommodation_Response) ProtoReflect() protoreflect.Message {
	mi := &file_accommodation_accommodation_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AM_CreateAccommodation_Response.ProtoReflect.Descriptor instead.
func (*AM_CreateAccommodation_Response) Descriptor() ([]byte, []int) {
	return file_accommodation_accommodation_service_proto_rawDescGZIP(), []int{3}
}

func (x *AM_CreateAccommodation_Response) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AM_GetAllPeriodsByAccommodation_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccommodationId string `protobuf:"bytes,1,opt,name=accommodationId,proto3" json:"accommodationId,omitempty"`
}

func (x *AM_GetAllPeriodsByAccommodation_Request) Reset() {
	*x = AM_GetAllPeriodsByAccommodation_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accommodation_accommodation_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AM_GetAllPeriodsByAccommodation_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AM_GetAllPeriodsByAccommodation_Request) ProtoMessage() {}

func (x *AM_GetAllPeriodsByAccommodation_Request) ProtoReflect() protoreflect.Message {
	mi := &file_accommodation_accommodation_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AM_GetAllPeriodsByAccommodation_Request.ProtoReflect.Descriptor instead.
func (*AM_GetAllPeriodsByAccommodation_Request) Descriptor() ([]byte, []int) {
	return file_accommodation_accommodation_service_proto_rawDescGZIP(), []int{4}
}

func (x *AM_GetAllPeriodsByAccommodation_Request) GetAccommodationId() string {
	if x != nil {
		return x.AccommodationId
	}
	return ""
}

type AM_GetAllPeriodsByAccommodation_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*PeriodDTO `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *AM_GetAllPeriodsByAccommodation_Response) Reset() {
	*x = AM_GetAllPeriodsByAccommodation_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accommodation_accommodation_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AM_GetAllPeriodsByAccommodation_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AM_GetAllPeriodsByAccommodation_Response) ProtoMessage() {}

func (x *AM_GetAllPeriodsByAccommodation_Response) ProtoReflect() protoreflect.Message {
	mi := &file_accommodation_accommodation_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AM_GetAllPeriodsByAccommodation_Response.ProtoReflect.Descriptor instead.
func (*AM_GetAllPeriodsByAccommodation_Response) Descriptor() ([]byte, []int) {
	return file_accommodation_accommodation_service_proto_rawDescGZIP(), []int{5}
}

func (x *AM_GetAllPeriodsByAccommodation_Response) GetData() []*PeriodDTO {
	if x != nil {
		return x.Data
	}
	return nil
}

type AM_CreatePeriod_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start           string `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End             string `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	AccommodationId string `protobuf:"bytes,3,opt,name=accommodationId,proto3" json:"accommodationId,omitempty"`
	UserId          string `protobuf:"bytes,4,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *AM_CreatePeriod_Request) Reset() {
	*x = AM_CreatePeriod_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accommodation_accommodation_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AM_CreatePeriod_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AM_CreatePeriod_Request) ProtoMessage() {}

func (x *AM_CreatePeriod_Request) ProtoReflect() protoreflect.Message {
	mi := &file_accommodation_accommodation_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AM_CreatePeriod_Request.ProtoReflect.Descriptor instead.
func (*AM_CreatePeriod_Request) Descriptor() ([]byte, []int) {
	return file_accommodation_accommodation_service_proto_rawDescGZIP(), []int{6}
}

func (x *AM_CreatePeriod_Request) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *AM_CreatePeriod_Request) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *AM_CreatePeriod_Request) GetAccommodationId() string {
	if x != nil {
		return x.AccommodationId
	}
	return ""
}

func (x *AM_CreatePeriod_Request) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AM_CreatePeriod_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *AM_CreatePeriod_Response) Reset() {
	*x = AM_CreatePeriod_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accommodation_accommodation_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AM_CreatePeriod_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AM_CreatePeriod_Response) ProtoMessage() {}

func (x *AM_CreatePeriod_Response) ProtoReflect() protoreflect.Message {
	mi := &file_accommodation_accommodation_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AM_CreatePeriod_Response.ProtoReflect.Descriptor instead.
func (*AM_CreatePeriod_Response) Descriptor() ([]byte, []int) {
	return file_accommodation_accommodation_service_proto_rawDescGZIP(), []int{7}
}

func (x *AM_CreatePeriod_Response) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AM_GetAllDiscountsByAccommodation_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccommodationId string `protobuf:"bytes,1,opt,name=accommodationId,proto3" json:"accommodationId,omitempty"`
}

func (x *AM_GetAllDiscountsByAccommodation_Request) Reset() {
	*x = AM_GetAllDiscountsByAccommodation_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accommodation_accommodation_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AM_GetAllDiscountsByAccommodation_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AM_GetAllDiscountsByAccommodation_Request) ProtoMessage() {}

func (x *AM_GetAllDiscountsByAccommodation_Request) ProtoReflect() protoreflect.Message {
	mi := &file_accommodation_accommodation_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AM_GetAllDiscountsByAccommodation_Request.ProtoReflect.Descriptor instead.
func (*AM_GetAllDiscountsByAccommodation_Request) Descriptor() ([]byte, []int) {
	return file_accommodation_accommodation_service_proto_rawDescGZIP(), []int{8}
}

func (x *AM_GetAllDiscountsByAccommodation_Request) GetAccommodationId() string {
	if x != nil {
		return x.AccommodationId
	}
	return ""
}

type AM_GetAllDiscountsByAccommodation_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*DiscountDTO `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *AM_GetAllDiscountsByAccommodation_Response) Reset() {
	*x = AM_GetAllDiscountsByAccommodation_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accommodation_accommodation_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AM_GetAllDiscountsByAccommodation_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AM_GetAllDiscountsByAccommodation_Response) ProtoMessage() {}

func (x *AM_GetAllDiscountsByAccommodation_Response) ProtoReflect() protoreflect.Message {
	mi := &file_accommodation_accommodation_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AM_GetAllDiscountsByAccommodation_Response.ProtoReflect.Descriptor instead.
func (*AM_GetAllDiscountsByAccommodation_Response) Descriptor() ([]byte, []int) {
	return file_accommodation_accommodation_service_proto_rawDescGZIP(), []int{9}
}

func (x *AM_GetAllDiscountsByAccommodation_Response) GetData() []*DiscountDTO {
	if x != nil {
		return x.Data
	}
	return nil
}

type AM_GetAllDiscountsByAccommodationAndInterval_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccommodationId string `protobuf:"bytes,1,opt,name=accommodationId,proto3" json:"accommodationId,omitempty"`
	Start           string `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End             string `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	UserId          string `protobuf:"bytes,4,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *AM_GetAllDiscountsByAccommodationAndInterval_Request) Reset() {
	*x = AM_GetAllDiscountsByAccommodationAndInterval_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accommodation_accommodation_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AM_GetAllDiscountsByAccommodationAndInterval_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AM_GetAllDiscountsByAccommodationAndInterval_Request) ProtoMessage() {}

func (x *AM_GetAllDiscountsByAccommodationAndInterval_Request) ProtoReflect() protoreflect.Message {
	mi := &file_accommodation_accommodation_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AM_GetAllDiscountsByAccommodationAndInterval_Request.ProtoReflect.Descriptor instead.
func (*AM_GetAllDiscountsByAccommodationAndInterval_Request) Descriptor() ([]byte, []int) {
	return file_accommodation_accommodation_service_proto_rawDescGZIP(), []int{10}
}

func (x *AM_GetAllDiscountsByAccommodationAndInterval_Request) GetAccommodationId() string {
	if x != nil {
		return x.AccommodationId
	}
	return ""
}

func (x *AM_GetAllDiscountsByAccommodationAndInterval_Request) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *AM_GetAllDiscountsByAccommodationAndInterval_Request) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *AM_GetAllDiscountsByAccommodationAndInterval_Request) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AM_GetAllDiscountsByAccommodationAndInterval_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*DiscountDTO `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *AM_GetAllDiscountsByAccommodationAndInterval_Response) Reset() {
	*x = AM_GetAllDiscountsByAccommodationAndInterval_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accommodation_accommodation_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AM_GetAllDiscountsByAccommodationAndInterval_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AM_GetAllDiscountsByAccommodationAndInterval_Response) ProtoMessage() {}

func (x *AM_GetAllDiscountsByAccommodationAndInterval_Response) ProtoReflect() protoreflect.Message {
	mi := &file_accommodation_accommodation_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AM_GetAllDiscountsByAccommodationAndInterval_Response.ProtoReflect.Descriptor instead.
func (*AM_GetAllDiscountsByAccommodationAndInterval_Response) Descriptor() ([]byte, []int) {
	return file_accommodation_accommodation_service_proto_rawDescGZIP(), []int{11}
}

func (x *AM_GetAllDiscountsByAccommodationAndInterval_Response) GetData() []*DiscountDTO {
	if x != nil {
		return x.Data
	}
	return nil
}

type AM_CreateDiscount_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start           string  `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End             string  `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	AccommodationId string  `protobuf:"bytes,3,opt,name=accommodationId,proto3" json:"accommodationId,omitempty"`
	UserId          string  `protobuf:"bytes,4,opt,name=userId,proto3" json:"userId,omitempty"`
	Discount        float64 `protobuf:"fixed64,5,opt,name=discount,proto3" json:"discount,omitempty"`
}

func (x *AM_CreateDiscount_Request) Reset() {
	*x = AM_CreateDiscount_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accommodation_accommodation_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AM_CreateDiscount_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AM_CreateDiscount_Request) ProtoMessage() {}

func (x *AM_CreateDiscount_Request) ProtoReflect() protoreflect.Message {
	mi := &file_accommodation_accommodation_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AM_CreateDiscount_Request.ProtoReflect.Descriptor instead.
func (*AM_CreateDiscount_Request) Descriptor() ([]byte, []int) {
	return file_accommodation_accommodation_service_proto_rawDescGZIP(), []int{12}
}

func (x *AM_CreateDiscount_Request) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *AM_CreateDiscount_Request) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *AM_CreateDiscount_Request) GetAccommodationId() string {
	if x != nil {
		return x.AccommodationId
	}
	return ""
}

func (x *AM_CreateDiscount_Request) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AM_CreateDiscount_Request) GetDiscount() float64 {
	if x != nil {
		return x.Discount
	}
	return 0
}

type AM_CreateDiscount_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *AM_CreateDiscount_Response) Reset() {
	*x = AM_CreateDiscount_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accommodation_accommodation_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AM_CreateDiscount_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AM_CreateDiscount_Response) ProtoMessage() {}

func (x *AM_CreateDiscount_Response) ProtoReflect() protoreflect.Message {
	mi := &file_accommodation_accommodation_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AM_CreateDiscount_Response.ProtoReflect.Descriptor instead.
func (*AM_CreateDiscount_Response) Descriptor() ([]byte, []int) {
	return file_accommodation_accommodation_service_proto_rawDescGZIP(), []int{13}
}

func (x *AM_CreateDiscount_Response) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AccommodationDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Benefits  string  `protobuf:"bytes,3,opt,name=benefits,proto3" json:"benefits,omitempty"`
	MinGuests int32   `protobuf:"varint,4,opt,name=minGuests,proto3" json:"minGuests,omitempty"`
	MaxGuests int32   `protobuf:"varint,5,opt,name=maxGuests,proto3" json:"maxGuests,omitempty"`
	BasePrice float64 `protobuf:"fixed64,6,opt,name=basePrice,proto3" json:"basePrice,omitempty"`
}

func (x *AccommodationDTO) Reset() {
	*x = AccommodationDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accommodation_accommodation_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccommodationDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccommodationDTO) ProtoMessage() {}

func (x *AccommodationDTO) ProtoReflect() protoreflect.Message {
	mi := &file_accommodation_accommodation_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccommodationDTO.ProtoReflect.Descriptor instead.
func (*AccommodationDTO) Descriptor() ([]byte, []int) {
	return file_accommodation_accommodation_service_proto_rawDescGZIP(), []int{14}
}

func (x *AccommodationDTO) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccommodationDTO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccommodationDTO) GetBenefits() string {
	if x != nil {
		return x.Benefits
	}
	return ""
}

func (x *AccommodationDTO) GetMinGuests() int32 {
	if x != nil {
		return x.MinGuests
	}
	return 0
}

func (x *AccommodationDTO) GetMaxGuests() int32 {
	if x != nil {
		return x.MaxGuests
	}
	return 0
}

func (x *AccommodationDTO) GetBasePrice() float64 {
	if x != nil {
		return x.BasePrice
	}
	return 0
}

type PeriodDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Start           string `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End             string `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	AccommodationId string `protobuf:"bytes,4,opt,name=accommodationId,proto3" json:"accommodationId,omitempty"`
	UserId          string `protobuf:"bytes,5,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *PeriodDTO) Reset() {
	*x = PeriodDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accommodation_accommodation_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeriodDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeriodDTO) ProtoMessage() {}

func (x *PeriodDTO) ProtoReflect() protoreflect.Message {
	mi := &file_accommodation_accommodation_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeriodDTO.ProtoReflect.Descriptor instead.
func (*PeriodDTO) Descriptor() ([]byte, []int) {
	return file_accommodation_accommodation_service_proto_rawDescGZIP(), []int{15}
}

func (x *PeriodDTO) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PeriodDTO) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *PeriodDTO) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *PeriodDTO) GetAccommodationId() string {
	if x != nil {
		return x.AccommodationId
	}
	return ""
}

func (x *PeriodDTO) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DiscountDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Start           string  `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End             string  `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	AccommodationId string  `protobuf:"bytes,4,opt,name=accommodationId,proto3" json:"accommodationId,omitempty"`
	UserId          string  `protobuf:"bytes,5,opt,name=userId,proto3" json:"userId,omitempty"`
	Discount        float64 `protobuf:"fixed64,6,opt,name=discount,proto3" json:"discount,omitempty"`
}

func (x *DiscountDTO) Reset() {
	*x = DiscountDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accommodation_accommodation_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiscountDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscountDTO) ProtoMessage() {}

func (x *DiscountDTO) ProtoReflect() protoreflect.Message {
	mi := &file_accommodation_accommodation_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscountDTO.ProtoReflect.Descriptor instead.
func (*DiscountDTO) Descriptor() ([]byte, []int) {
	return file_accommodation_accommodation_service_proto_rawDescGZIP(), []int{16}
}

func (x *DiscountDTO) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DiscountDTO) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *DiscountDTO) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *DiscountDTO) GetAccommodationId() string {
	if x != nil {
		return x.AccommodationId
	}
	return ""
}

func (x *DiscountDTO) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DiscountDTO) GetDiscount() float64 {
	if x != nil {
		return x.Discount
	}
	return 0
}

var File_accommodation_accommodation_service_proto protoreflect.FileDescriptor

var file_accommodation_accommodation_service_proto_rawDesc = []byte{
	0x0a, 0x29, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f,
	0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x21, 0x0a, 0x1f, 0x41,
	0x4d, 0x5f, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x49,
	0x0a, 0x20, 0x41, 0x4d, 0x5f, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x44, 0x54, 0x4f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xaa, 0x01, 0x0a, 0x1e, 0x41, 0x4d,
	0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x62, 0x65, 0x6e, 0x65, 0x66, 0x69, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x62, 0x65, 0x6e, 0x65, 0x66, 0x69, 0x74, 0x73, 0x12, 0x1c, 0x0a, 0x09,
	0x6d, 0x69, 0x6e, 0x47, 0x75, 0x65, 0x73, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x6d, 0x69, 0x6e, 0x47, 0x75, 0x65, 0x73, 0x74, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61,
	0x78, 0x47, 0x75, 0x65, 0x73, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d,
	0x61, 0x78, 0x47, 0x75, 0x65, 0x73, 0x74, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x65,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x62, 0x61, 0x73,
	0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x22, 0x31, 0x0a, 0x1f, 0x41, 0x4d, 0x5f, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x53, 0x0a, 0x27, 0x41, 0x4d, 0x5f,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x73, 0x42, 0x79, 0x41,
	0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x61,
	0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x4a,
	0x0a, 0x28, 0x41, 0x4d, 0x5f, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x65, 0x72, 0x69, 0x6f,
	0x64, 0x73, 0x42, 0x79, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x50, 0x65, 0x72, 0x69, 0x6f,
	0x64, 0x44, 0x54, 0x4f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x83, 0x01, 0x0a, 0x17, 0x41,
	0x4d, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x5f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x12, 0x28,
	0x0a, 0x0f, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x2a, 0x0a, 0x18, 0x41, 0x4d, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x65, 0x72,
	0x69, 0x6f, 0x64, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x55, 0x0a, 0x29,
	0x41, 0x4d, 0x5f, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x73, 0x42, 0x79, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x61, 0x63, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0f, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x22, 0x4e, 0x0a, 0x2a, 0x41, 0x4d, 0x5f, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x42, 0x79, 0x41, 0x63, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x20, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x54, 0x4f, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0xa0, 0x01, 0x0a, 0x34, 0x41, 0x4d, 0x5f, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x42, 0x79, 0x41, 0x63, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6e, 0x64, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x76, 0x61, 0x6c, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x0f,
	0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x65, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x59, 0x0a, 0x35, 0x41, 0x4d, 0x5f, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x42, 0x79, 0x41, 0x63,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6e, 0x64, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x20, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x54, 0x4f, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0xa1, 0x01, 0x0a, 0x19, 0x41, 0x4d, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44,
	0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x61, 0x63, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0f, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x64, 0x69, 0x73,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2c, 0x0a, 0x1a, 0x41, 0x4d, 0x5f, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0xac, 0x01, 0x0a, 0x10, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x54, 0x4f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x62, 0x65, 0x6e, 0x65, 0x66, 0x69, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x62, 0x65, 0x6e, 0x65, 0x66, 0x69, 0x74, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x69, 0x6e, 0x47,
	0x75, 0x65, 0x73, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x69, 0x6e,
	0x47, 0x75, 0x65, 0x73, 0x74, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x78, 0x47, 0x75, 0x65,
	0x73, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x61, 0x78, 0x47, 0x75,
	0x65, 0x73, 0x74, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x65, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x62, 0x61, 0x73, 0x65, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x22, 0x85, 0x01, 0x0a, 0x09, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x44, 0x54, 0x4f,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x61, 0x63, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0f, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0xa3, 0x01, 0x0a, 0x0b, 0x44,
	0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x54, 0x4f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65,
	0x6e, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x61, 0x63, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x32, 0xf8, 0x05, 0x0a, 0x14, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5d, 0x0a, 0x14, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x20, 0x2e, 0x41, 0x4d, 0x5f, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x41, 0x63, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x41, 0x4d, 0x5f, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x41,
	0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1f, 0x2e, 0x41, 0x4d, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x20, 0x2e, 0x41, 0x4d, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x75, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x65,
	0x72, 0x69, 0x6f, 0x64, 0x73, 0x42, 0x79, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x2e, 0x41, 0x4d, 0x5f, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x73, 0x42, 0x79, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29,
	0x2e, 0x41, 0x4d, 0x5f, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64,
	0x73, 0x42, 0x79, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0c, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x18, 0x2e, 0x41, 0x4d,
	0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x5f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x41, 0x4d, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x7b, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x44, 0x69, 0x73, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x73, 0x42, 0x79, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x2e, 0x41, 0x4d, 0x5f, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x42, 0x79, 0x41, 0x63, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x2b, 0x2e, 0x41, 0x4d, 0x5f, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x44, 0x69, 0x73, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x73, 0x42, 0x79, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x9c, 0x01, 0x0a, 0x29, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x73, 0x42, 0x79, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x41, 0x6e, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x12, 0x35, 0x2e,
	0x41, 0x4d, 0x5f, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x73, 0x42, 0x79, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x41, 0x6e, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x5f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x36, 0x2e, 0x41, 0x4d, 0x5f, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x42, 0x79, 0x41, 0x63, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6e, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x76, 0x61, 0x6c, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4b,
	0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x1a, 0x2e, 0x41, 0x4d, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x41,
	0x4d, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x15, 0x5a, 0x13, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_accommodation_accommodation_service_proto_rawDescOnce sync.Once
	file_accommodation_accommodation_service_proto_rawDescData = file_accommodation_accommodation_service_proto_rawDesc
)

func file_accommodation_accommodation_service_proto_rawDescGZIP() []byte {
	file_accommodation_accommodation_service_proto_rawDescOnce.Do(func() {
		file_accommodation_accommodation_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_accommodation_accommodation_service_proto_rawDescData)
	})
	return file_accommodation_accommodation_service_proto_rawDescData
}

var file_accommodation_accommodation_service_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_accommodation_accommodation_service_proto_goTypes = []interface{}{
	(*AM_GetAllAccommodations_Request)(nil),                       // 0: AM_GetAllAccommodations_Request
	(*AM_GetAllAccommodations_Response)(nil),                      // 1: AM_GetAllAccommodations_Response
	(*AM_CreateAccommodation_Request)(nil),                        // 2: AM_CreateAccommodation_Request
	(*AM_CreateAccommodation_Response)(nil),                       // 3: AM_CreateAccommodation_Response
	(*AM_GetAllPeriodsByAccommodation_Request)(nil),               // 4: AM_GetAllPeriodsByAccommodation_Request
	(*AM_GetAllPeriodsByAccommodation_Response)(nil),              // 5: AM_GetAllPeriodsByAccommodation_Response
	(*AM_CreatePeriod_Request)(nil),                               // 6: AM_CreatePeriod_Request
	(*AM_CreatePeriod_Response)(nil),                              // 7: AM_CreatePeriod_Response
	(*AM_GetAllDiscountsByAccommodation_Request)(nil),             // 8: AM_GetAllDiscountsByAccommodation_Request
	(*AM_GetAllDiscountsByAccommodation_Response)(nil),            // 9: AM_GetAllDiscountsByAccommodation_Response
	(*AM_GetAllDiscountsByAccommodationAndInterval_Request)(nil),  // 10: AM_GetAllDiscountsByAccommodationAndInterval_Request
	(*AM_GetAllDiscountsByAccommodationAndInterval_Response)(nil), // 11: AM_GetAllDiscountsByAccommodationAndInterval_Response
	(*AM_CreateDiscount_Request)(nil),                             // 12: AM_CreateDiscount_Request
	(*AM_CreateDiscount_Response)(nil),                            // 13: AM_CreateDiscount_Response
	(*AccommodationDTO)(nil),                                      // 14: AccommodationDTO
	(*PeriodDTO)(nil),                                             // 15: PeriodDTO
	(*DiscountDTO)(nil),                                           // 16: DiscountDTO
}
var file_accommodation_accommodation_service_proto_depIdxs = []int32{
	14, // 0: AM_GetAllAccommodations_Response.data:type_name -> AccommodationDTO
	15, // 1: AM_GetAllPeriodsByAccommodation_Response.data:type_name -> PeriodDTO
	16, // 2: AM_GetAllDiscountsByAccommodation_Response.data:type_name -> DiscountDTO
	16, // 3: AM_GetAllDiscountsByAccommodationAndInterval_Response.data:type_name -> DiscountDTO
	0,  // 4: AccommodationService.GetAllAccommodations:input_type -> AM_GetAllAccommodations_Request
	2,  // 5: AccommodationService.CreateAccommodation:input_type -> AM_CreateAccommodation_Request
	4,  // 6: AccommodationService.GetAllPeriodsByAccommodation:input_type -> AM_GetAllPeriodsByAccommodation_Request
	6,  // 7: AccommodationService.CreatePeriod:input_type -> AM_CreatePeriod_Request
	8,  // 8: AccommodationService.GetAllDiscountsByAccommodation:input_type -> AM_GetAllDiscountsByAccommodation_Request
	10, // 9: AccommodationService.GetAllDiscountsByAccommodationAndInterval:input_type -> AM_GetAllDiscountsByAccommodationAndInterval_Request
	12, // 10: AccommodationService.CreateDiscount:input_type -> AM_CreateDiscount_Request
	1,  // 11: AccommodationService.GetAllAccommodations:output_type -> AM_GetAllAccommodations_Response
	3,  // 12: AccommodationService.CreateAccommodation:output_type -> AM_CreateAccommodation_Response
	5,  // 13: AccommodationService.GetAllPeriodsByAccommodation:output_type -> AM_GetAllPeriodsByAccommodation_Response
	7,  // 14: AccommodationService.CreatePeriod:output_type -> AM_CreatePeriod_Response
	9,  // 15: AccommodationService.GetAllDiscountsByAccommodation:output_type -> AM_GetAllDiscountsByAccommodation_Response
	11, // 16: AccommodationService.GetAllDiscountsByAccommodationAndInterval:output_type -> AM_GetAllDiscountsByAccommodationAndInterval_Response
	13, // 17: AccommodationService.CreateDiscount:output_type -> AM_CreateDiscount_Response
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_accommodation_accommodation_service_proto_init() }
func file_accommodation_accommodation_service_proto_init() {
	if File_accommodation_accommodation_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_accommodation_accommodation_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AM_GetAllAccommodations_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accommodation_accommodation_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AM_GetAllAccommodations_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accommodation_accommodation_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AM_CreateAccommodation_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accommodation_accommodation_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AM_CreateAccommodation_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accommodation_accommodation_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AM_GetAllPeriodsByAccommodation_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accommodation_accommodation_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AM_GetAllPeriodsByAccommodation_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accommodation_accommodation_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AM_CreatePeriod_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accommodation_accommodation_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AM_CreatePeriod_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accommodation_accommodation_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AM_GetAllDiscountsByAccommodation_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accommodation_accommodation_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AM_GetAllDiscountsByAccommodation_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accommodation_accommodation_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AM_GetAllDiscountsByAccommodationAndInterval_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accommodation_accommodation_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AM_GetAllDiscountsByAccommodationAndInterval_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accommodation_accommodation_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AM_CreateDiscount_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accommodation_accommodation_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AM_CreateDiscount_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accommodation_accommodation_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccommodationDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accommodation_accommodation_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PeriodDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accommodation_accommodation_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiscountDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_accommodation_accommodation_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_accommodation_accommodation_service_proto_goTypes,
		DependencyIndexes: file_accommodation_accommodation_service_proto_depIdxs,
		MessageInfos:      file_accommodation_accommodation_service_proto_msgTypes,
	}.Build()
	File_accommodation_accommodation_service_proto = out.File
	file_accommodation_accommodation_service_proto_rawDesc = nil
	file_accommodation_accommodation_service_proto_goTypes = nil
	file_accommodation_accommodation_service_proto_depIdxs = nil
}
